version: "3"

services:
  app:
    container_name: nuxtjs
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    image: transcendance/nuxtjs
    build:
      context: ./app
    volumes:
      - type: bind
        source: ./app
        target: /home/node/app
      - type: volume
        target: /home/node/app/node_modules
    ports:
      - 8000:8000

  api:
    container_name: nestjs
    image: transcendance/nestjs
    build:
      context: ./api
    volumes:
      - type: bind
        source: ./api
        target: /home/node/app
      - type: volume
        target: /home/node/app/node_modules
    # Expose API for clients using or SPA app
    # Api Gateway or reverse proxy may be overkill for this type of project
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend:
