version: "3"

services:
  app:
    container_name: nuxtjs
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    image: transcendance/nuxtjs
    build:
      context: ./app
    volumes:
      - type: bind
        source: ./app
        target: /home/node/app
      - type: volume
        target: /home/node/app/node_modules
    ports:
      - 8000:8000
      - 24678:24678

  api:
    container_name: nestjs
    image: transcendance/nestjs
    build:
      context: ./api
    volumes:
      - type: bind
        source: ./api
        target: /home/node/app
      - type: volume
        target: /home/node/app/node_modules
    # Expose API for clients using or SPA app
    # Api Gateway or reverse proxy may be overkill for this type of project
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      - db
    # environment:
    #   # - DEBUG=*

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

volumes:
  db:
    driver: local

networks:
  backend:
